### PR TITLE
Package and workflow updates

### PR DESCRIPTION
**Pull request by DylanTackoor**
solves https://github.com/EmuDeck/emudeck-electron/issues/1

- syncs `package-lock.json` to `package.json`
- adds a `.nvmrc` for the CI env + people with nvm configured in their terminals :)
- caches `node_modules` in CI & only reinstalls if `package-lock.json` changes
- specifies x64 builds cuz i got an arm build on my mac

### CODE REVIEW

**Comment by dragoonDorise** [comment]
Hi @DylanTackoor , I'm sorry to tell you this but we are not accepting PR at this moment, this is still in early development, we will star accepting PR on the future, I won't close all of your PR so we can take a look and implement them in the future, but in the meantime don't send us more UR, I don't want to do all that work for nothing!

**Comment by DylanTackoor** [comment]
@dragoonDorise I'll hold off on submitting PRs, but instead of re-implementing my work in the future could the current stuff be merged or nah?

**Comment by dragoonDorise** [comment]
Hi @DylanTackoor , I've added your changes manually since the files changed a bit since your PR, so I'm closing the PR instead of merging it but your changes are applied :). Thanks!!

PS: I'll be doing the same with your TS PR as soon as I manage to start migrating the project to TS, since I'm a JS guy I'm gonna need some time to learn some TS basics before going 100% the TS route.

**Comment by DylanTackoor** [comment]
@dragoonDorise glad it could help! 😄

**Pull request closed without merging**
